export const logos = {
  apple: "https://s3-symbol-logo.tradingview.com/apple.svg",
  sp: "https://s3-symbol-logo.tradingview.com/indices/s-and-p-500.svg",
  nasdaq: "https://s3-symbol-logo.tradingview.com/indices/nasdaq-100.svg",
  bitcoin: "https://s3-symbol-logo.tradingview.com/crypto/XTVCBTC.svg",
  dollar: "https://s3-symbol-logo.tradingview.com/indices/u-s-dollar-index.svg",
  dow: "https://s3-symbol-logo.tradingview.com/indices/dow-30.svg",
  russell: "https://s3-symbol-logo.tradingview.com/indices/russell-2000.svg",
  tesla: "https://s3-symbol-logo.tradingview.com/tesla.svg",
  wallmart: "https://s3-symbol-logo.tradingview.com/walmart.svg",
  google: "https://s3-symbol-logo.tradingview.com/alphabet.svg",
  jj: "https://s3-symbol-logo.tradingview.com/johnson-and-johnson.svg",
  berkshire: "https://s3-symbol-logo.tradingview.com/berkshire-hathaway.svg",
  ethereum: "https://s3-symbol-logo.tradingview.com/crypto/XTVCETH.svg",
  bnb: "https://s3-symbol-logo.tradingview.com/crypto/XTVCBNB.svg",
  solana: "https://s3-symbol-logo.tradingview.com/crypto/XTVCSOL.svg",
  avalanche: "https://s3-symbol-logo.tradingview.com/crypto/XTVCSOL.svg",
  marketcap: "https://s3-symbol-logo.tradingview.com/crypto/XTVCSOL.svg",
  usa: "https://s3-symbol-logo.tradingview.com/country/US.svg",
  gold: "https://s3-symbol-logo.tradingview.com/metal/gold.svg",
  crude: "https://s3-symbol-logo.tradingview.com/crude-oil.svg",
  silver: "https://s3-symbol-logo.tradingview.com/metal/silver.svg",
  wheat: "https://s3-symbol-logo.tradingview.com/wheat.svg",
  gas: "https://s3-symbol-logo.tradingview.com/natural-gas.svg",
  euro: "https://s3-symbol-logo.tradingview.com/country/EU.svg",
  japan: "https://s3-symbol-logo.tradingview.com/country/JP.svg",
  uk: "https://s3-symbol-logo.tradingview.com/country/GB.svg",
};
